import bcrypt from 'bcrypt'

const usuarios = [
    // Admins de la plataforma
    {
        name: 'Jonathan Muñoz',
        paterno: '',
        materno: 'Villarroel',
        genero: 'masculino',
        email: 'jona@correo.com',
        telefono: '68391241',
        password: bcrypt.hashSync('password', 10),
        cuentaId: 5,
        fechaCreacion: '05-09-2024 12:50:46',
        token: '',
        confirmado: 1
    },
    {
        name: 'David',
        paterno: '',
        materno: '',
        genero: 'masculino',
        email: 'david@correo.com',
        telefono: '123123',
        password: bcrypt.hashSync('password', 10),
        cuentaId: 5,
        fechaCreacion: '05-09-2024 14:50:46',
        token: '',
        confirmado: 1
    },

    // Usuarios Normales
    {
        name: 'Juan',
        paterno: 'Pérez',
        materno: 'García',
        genero: 'masculino',
        email: 'juan.perez@correo.com',
        telefono: '123456789',
        password: bcrypt.hashSync('password', 10),
        cuentaId: 1,
        fechaCreacion: '17-10-2024 16:50:46',
        token: '',
        confirmado: 1
      },
      {
        name: 'María',
        paterno: 'Gómez',
        materno: 'López',
        genero: 'femenino',
        email: 'maria.gomez@correo.com',
        telefono: '987654321',
        password: bcrypt.hashSync('password', 10),
        cuentaId: 1,
        fechaCreacion: '10-10-2024 16:51:30',
        token: '',
        confirmado: 1
      },
      {
        name: 'Carlos',
        paterno: 'Sánchez',
        materno: 'Martínez',
        genero: 'masculino',
        email: 'carlos.sanchez@correo.com',
        telefono: '1122334455',
        password: bcrypt.hashSync('password', 10),
        cuentaId: 1,
        fechaCreacion: '05-10-2024 16:52:15',
        token: '',
        confirmado: 1
      },
      {
        name: 'Ana',
        paterno: 'Martínez',
        materno: 'Fernández',
        genero: 'femenino',
        email: 'ana.martinez@correo.com',
        telefono: '6677889900',
        password: bcrypt.hashSync('password', 10),
        cuentaId: 1,
        fechaCreacion: '05-09-2024 16:53:00',
        token: '',
        confirmado: 1
      },
      {
        name: 'José',
        paterno: 'Rodríguez',
        materno: 'Hernández',
        genero: 'masculino',
        email: 'jose.rodriguez@correo.com',
        telefono: '3344556677',
        password: bcrypt.hashSync('password', 10),
        cuentaId: 1,
        fechaCreacion: '05-09-2024 16:53:45',
        token: '',
        confirmado: 1
      },
      {
        name: 'Laura',
        paterno: 'Fernández',
        materno: 'García',
        genero: 'femenino',
        email: 'laura.fernandez@correo.com',
        telefono: '5566778899',
        password: bcrypt.hashSync('password', 10),
        cuentaId: 1,
        fechaCreacion: '05-09-2024 16:54:30',
        token: '',
        confirmado: 1
      },
      {
        name: 'Pedro',
        paterno: 'Morales',
        materno: 'Pérez',
        genero: 'masculino',
        email: 'pedro.morales@correo.com',
        telefono: '7788990011',
        password: bcrypt.hashSync('password', 10),
        cuentaId: 1,
        fechaCreacion: '05-09-2024 16:55:15',
        token: '',
        confirmado: 1
      },
      {
        name: 'Lucía',
        paterno: 'García',
        materno: 'Sánchez',
        genero: 'femenino',
        email: 'lucia.garcia@correo.com',
        telefono: '1122112233',
        password: bcrypt.hashSync('password', 10),
        cuentaId: 1,
        fechaCreacion: '05-09-2024 16:56:00',
        token: '',
        confirmado: 1
      },
      {
        name: 'Miguel',
        paterno: 'Torres',
        materno: 'Hernández',
        genero: 'masculino',
        email: 'miguel.torres@correo.com',
        telefono: '3344551234',
        password: bcrypt.hashSync('password', 10),
        cuentaId: 1,
        fechaCreacion: '05-09-2024 16:56:45',
        token: '',
        confirmado: 1
      },
      {
        name: 'Sofía',
        paterno: 'Ramírez',
        materno: 'Gómez',
        genero: 'femenino',
        email: 'sofia.ramirez@correo.com',
        telefono: '5566447788',
        password: bcrypt.hashSync('password', 10),
        cuentaId: 1,
        fechaCreacion: '05-09-2024 16:57:30',
        token: '',
        confirmado: 1
      },
      {
        name: 'Isabel',
        paterno: 'Ramos',
        materno: 'Vega',
        genero: 'femenino',
        email: 'isabel.ramos@correo.com',
        telefono: '123456780',
        password: bcrypt.hashSync('password', 10),
        cuentaId: 1,
        fechaCreacion: '06-09-2024 10:00:00',
        token: '',
        confirmado: 1
      },
      {
        name: 'Alberto',
        paterno: 'Moreno',
        materno: 'Castro',
        genero: 'masculino',
        email: 'alberto.moreno@correo.com',
        telefono: '234567891',
        password: bcrypt.hashSync('password', 10),
        cuentaId: 1,
        fechaCreacion: '06-09-2024 10:05:00',
        token: '',
        confirmado: 1
      },
      {
        name: 'Patricia',
        paterno: 'Cruz',
        materno: 'Soto',
        genero: 'femenino',
        email: 'patricia.cruz@correo.com',
        telefono: '345678902',
        password: bcrypt.hashSync('password', 10),
        cuentaId: 1,
        fechaCreacion: '06-09-2024 10:10:00',
        token: '',
        confirmado: 1
      },
      {
        name: 'Ricardo',
        paterno: 'Luna',
        materno: 'Ortiz',
        genero: 'masculino',
        email: 'ricardo.luna@correo.com',
        telefono: '456789013',
        password: bcrypt.hashSync('password', 10),
        cuentaId: 1,
        fechaCreacion: '06-09-2024 10:15:00',
        token: '',
        confirmado: 1
      },
      {
        name: 'Adriana',
        paterno: 'Torres',
        materno: 'Flores',
        genero: 'femenino',
        email: 'adriana.torres@correo.com',
        telefono: '567890124',
        password: bcrypt.hashSync('password', 10),
        cuentaId: 1,
        fechaCreacion: '06-09-2024 10:20:00',
        token: '',
        confirmado: 1
      }
]

export default usuarios